name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright - Chromium
      run: |
        date --iso-8601=seconds
        npx playwright install chromium --with-deps
        date --iso-8601=seconds
      timeout-minutes: 15
    - name: Install Playwright - Firefox
      run: |
        date --iso-8601=seconds
        npx playwright install firefox --with-deps
        date --iso-8601=seconds
      timeout-minutes: 25
    - name: Install Playwright - WebKit
      run: |
        date --iso-8601=seconds
        npx playwright install webkit --with-deps
        date --iso-8601=seconds
      timeout-minutes: 25
    
    - name: Run Playwright tests
      run: npx playwright test --retries=2
    - uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
